[OK]"[OK]"[OK]"[OK][OK]
[OK]F[OK]u[OK]n[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK] [OK]a[OK]u[OK]x[OK]i[OK]l[OK]i[OK]a[OK]r[OK]e[OK]s[OK] [OK]p[OK]a[OK]r[OK]a[OK] [OK]e[OK]l[OK] [OK]p[OK]r[OK]o[OK]y[OK]e[OK]c[OK]t[OK]o[OK] [OK]A[OK]l[OK]e[OK]r[OK]t[OK]a[OK]M[OK]a[OK]t[OK]e[OK]r[OK]n[OK]a[OK][OK]
[OK]"[OK]"[OK]"[OK][OK]
[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]p[OK]a[OK]n[OK]d[OK]a[OK]s[OK] [OK]a[OK]s[OK] [OK]p[OK]d[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]n[OK]u[OK]m[OK]p[OK]y[OK] [OK]a[OK]s[OK] [OK]n[OK]p[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]p[OK]a[OK]t[OK]h[OK]l[OK]i[OK]b[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]P[OK]a[OK]t[OK]h[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]n[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]a[OK]r[OK]_[OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]d[OK]e[OK]p[OK]a[OK]r[OK]t[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]N[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]a[OK] [OK]c[OK]Ã[OK]³[OK]d[OK]i[OK]g[OK]o[OK] [OK]d[OK]e[OK] [OK]d[OK]e[OK]p[OK]a[OK]r[OK]t[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK] [OK]a[OK] [OK]2[OK] [OK]d[OK]Ã[OK]­[OK]g[OK]i[OK]t[OK]o[OK]s[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]p[OK]d[OK].[OK]i[OK]s[OK]n[OK]a[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]'[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK] [OK]=[OK] [OK]s[OK]t[OK]r[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK].[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]l[OK]e[OK]n[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK])[OK] [OK]=[OK]=[OK] [OK]1[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]'[OK]0[OK]'[OK] [OK]+[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK][[OK]:[OK]2[OK]][OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]n[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]a[OK]r[OK]_[OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]m[OK]u[OK]n[OK]i[OK]c[OK]i[OK]p[OK]i[OK]o[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]N[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]a[OK] [OK]c[OK]Ã[OK]³[OK]d[OK]i[OK]g[OK]o[OK] [OK]d[OK]e[OK] [OK]m[OK]u[OK]n[OK]i[OK]c[OK]i[OK]p[OK]i[OK]o[OK] [OK]a[OK] [OK]3[OK] [OK]d[OK]Ã[OK]­[OK]g[OK]i[OK]t[OK]o[OK]s[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]p[OK]d[OK].[OK]i[OK]s[OK]n[OK]a[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]'[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK] [OK]=[OK] [OK]s[OK]t[OK]r[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK])[OK].[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK].[OK]i[OK]s[OK]d[OK]i[OK]g[OK]i[OK]t[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK].[OK]z[OK]f[OK]i[OK]l[OK]l[OK]([OK]3[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK][[OK]-[OK]3[OK]:[OK]][OK] [OK]i[OK]f[OK] [OK]l[OK]e[OK]n[OK]([OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK])[OK] [OK]>[OK]=[OK] [OK]3[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]_[OK]s[OK]t[OK]r[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]c[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK]r[OK]_[OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK]([OK]s[OK]e[OK]r[OK]i[OK]e[OK],[OK] [OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]C[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK] [OK]e[OK]l[OK] [OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK] [OK]d[OK]e[OK] [OK]u[OK]n[OK]a[OK] [OK]s[OK]e[OK]r[OK]i[OK]e[OK] [OK]i[OK]g[OK]n[OK]o[OK]r[OK]a[OK]n[OK]d[OK]o[OK] [OK]N[OK]a[OK]N[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]n[OK]p[OK].[OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK]e[OK]([OK]s[OK]e[OK]r[OK]i[OK]e[OK].[OK]d[OK]r[OK]o[OK]p[OK]n[OK]a[OK]([OK])[OK],[OK] [OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK])[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]a[OK]r[OK]_[OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK]([OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK],[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK],[OK] [OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK],[OK] [OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]G[OK]u[OK]a[OK]r[OK]d[OK]a[OK] [OK]e[OK]l[OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK],[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK] [OK]y[OK] [OK]n[OK]o[OK]m[OK]b[OK]r[OK]e[OK]s[OK] [OK]d[OK]e[OK] [OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]s[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]=[OK] [OK]P[OK]a[OK]t[OK]h[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]w[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]d[OK]u[OK]m[OK]p[OK]([OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK],[OK] [OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]w[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]d[OK]u[OK]m[OK]p[OK]([OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK],[OK] [OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]w[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]d[OK]u[OK]m[OK]p[OK]([OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK],[OK] [OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]M[OK]o[OK]d[OK]e[OK]l[OK]o[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]a[OK]d[OK]o[OK] [OK]e[OK]n[OK] [OK]{[OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]c[OK]a[OK]r[OK]g[OK]a[OK]r[OK]_[OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]C[OK]a[OK]r[OK]g[OK]a[OK] [OK]e[OK]l[OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK],[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK] [OK]y[OK] [OK]n[OK]o[OK]m[OK]b[OK]r[OK]e[OK]s[OK] [OK]d[OK]e[OK] [OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]s[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]=[OK] [OK]P[OK]a[OK]t[OK]h[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]r[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK] [OK]=[OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]l[OK]o[OK]a[OK]d[OK]([OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]r[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK] [OK]=[OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]l[OK]o[OK]a[OK]d[OK]([OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]r[OK]u[OK]t[OK]a[OK]_[OK]b[OK]a[OK]s[OK]e[OK] [OK]/[OK] [OK]'[OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK].[OK]p[OK]k[OK]l[OK]'[OK],[OK] [OK]'[OK]r[OK]b[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK] [OK]=[OK] [OK]p[OK]i[OK]c[OK]k[OK]l[OK]e[OK].[OK]l[OK]o[OK]a[OK]d[OK]([OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]o[OK],[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]r[OK],[OK] [OK]f[OK]e[OK]a[OK]t[OK]u[OK]r[OK]e[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]f[OK]o[OK]r[OK]m[OK]a[OK]t[OK]e[OK]a[OK]r[OK]_[OK]n[OK]u[OK]m[OK]e[OK]r[OK]o[OK]([OK]n[OK]u[OK]m[OK]e[OK]r[OK]o[OK],[OK] [OK]d[OK]e[OK]c[OK]i[OK]m[OK]a[OK]l[OK]e[OK]s[OK]=[OK]2[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]F[OK]o[OK]r[OK]m[OK]a[OK]t[OK]e[OK]a[OK] [OK]n[OK]Ã[OK]º[OK]m[OK]e[OK]r[OK]o[OK]s[OK] [OK]c[OK]o[OK]n[OK] [OK]s[OK]e[OK]p[OK]a[OK]r[OK]a[OK]d[OK]o[OK]r[OK] [OK]d[OK]e[OK] [OK]m[OK]i[OK]l[OK]e[OK]s[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]p[OK]d[OK].[OK]i[OK]s[OK]n[OK]a[OK]([OK]n[OK]u[OK]m[OK]e[OK]r[OK]o[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]'[OK]N[OK]/[OK]A[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]f[OK]"[OK]{[OK]n[OK]u[OK]m[OK]e[OK]r[OK]o[OK]:[OK],[OK].[OK]{[OK]d[OK]e[OK]c[OK]i[OK]m[OK]a[OK]l[OK]e[OK]s[OK]}[OK]f[OK]}[OK]"[OK].[OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]([OK]'[OK],[OK]'[OK],[OK] [OK]'[OK]X[OK]'[OK])[OK].[OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]([OK]'[OK].[OK]'[OK],[OK] [OK]'[OK],[OK]'[OK])[OK].[OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]([OK]'[OK]X[OK]'[OK],[OK] [OK]'[OK].[OK]'[OK])[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]c[OK]l[OK]a[OK]s[OK]i[OK]f[OK]i[OK]c[OK]a[OK]r[OK]_[OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK]_[OK]m[OK]a[OK]n[OK]u[OK]a[OK]l[OK]([OK]r[OK]o[OK]w[OK],[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]C[OK]l[OK]a[OK]s[OK]i[OK]f[OK]i[OK]c[OK]a[OK] [OK]e[OK]l[OK] [OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK] [OK]d[OK]e[OK] [OK]m[OK]a[OK]n[OK]e[OK]r[OK]a[OK] [OK]m[OK]a[OK]n[OK]u[OK]a[OK]l[OK] [OK]b[OK]a[OK]s[OK]a[OK]d[OK]o[OK] [OK]e[OK]n[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]R[OK]e[OK]t[OK]o[OK]r[OK]n[OK]a[OK] [OK]1[OK] [OK]([OK]a[OK]l[OK]t[OK]o[OK] [OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK])[OK] [OK]o[OK] [OK]0[OK] [OK]([OK]b[OK]a[OK]j[OK]o[OK] [OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]d[OK]i[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK]_[OK]a[OK]l[OK]t[OK]o[OK]_[OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]t[OK]a[OK]s[OK]a[OK]_[OK]m[OK]o[OK]r[OK]t[OK]a[OK]l[OK]i[OK]d[OK]a[OK]d[OK]_[OK]f[OK]e[OK]t[OK]a[OK]l[OK]'[OK],[OK] [OK]0[OK])[OK] [OK]>[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][[OK]'[OK]t[OK]a[OK]s[OK]a[OK]_[OK]m[OK]o[OK]r[OK]t[OK]a[OK]l[OK]i[OK]d[OK]a[OK]d[OK]_[OK]f[OK]e[OK]t[OK]a[OK]l[OK]_[OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK]'[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]p[OK]r[OK]e[OK]s[OK]i[OK]o[OK]n[OK]_[OK]o[OK]b[OK]s[OK]t[OK]e[OK]t[OK]r[OK]i[OK]c[OK]a[OK]'[OK],[OK] [OK]0[OK])[OK] [OK]>[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][[OK]'[OK]p[OK]r[OK]e[OK]s[OK]i[OK]o[OK]n[OK]_[OK]o[OK]b[OK]s[OK]t[OK]e[OK]t[OK]r[OK]i[OK]c[OK]a[OK]_[OK]m[OK]a[OK]x[OK]'[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]p[OK]c[OK]t[OK]_[OK]s[OK]i[OK]n[OK]_[OK]s[OK]e[OK]g[OK]u[OK]r[OK]i[OK]d[OK]a[OK]d[OK]_[OK]s[OK]o[OK]c[OK]i[OK]a[OK]l[OK]'[OK],[OK] [OK]0[OK])[OK] [OK]>[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][[OK]'[OK]p[OK]c[OK]t[OK]_[OK]s[OK]i[OK]n[OK]_[OK]s[OK]e[OK]g[OK]u[OK]r[OK]i[OK]d[OK]a[OK]d[OK]_[OK]s[OK]o[OK]c[OK]i[OK]a[OK]l[OK]_[OK]m[OK]a[OK]x[OK]'[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]p[OK]c[OK]t[OK]_[OK]m[OK]a[OK]d[OK]r[OK]e[OK]s[OK]_[OK]a[OK]d[OK]o[OK]l[OK]e[OK]s[OK]c[OK]e[OK]n[OK]t[OK]e[OK]s[OK]'[OK],[OK] [OK]0[OK])[OK] [OK]>[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][[OK]'[OK]p[OK]c[OK]t[OK]_[OK]m[OK]a[OK]d[OK]r[OK]e[OK]s[OK]_[OK]a[OK]d[OK]o[OK]l[OK]e[OK]s[OK]c[OK]e[OK]n[OK]t[OK]e[OK]s[OK]_[OK]m[OK]a[OK]x[OK]'[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]n[OK]u[OK]m[OK]_[OK]i[OK]n[OK]s[OK]t[OK]i[OK]t[OK]u[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK]'[OK],[OK] [OK]1[OK])[OK] [OK]=[OK]=[OK] [OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]w[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]c[OK]a[OK]m[OK]a[OK]s[OK]_[OK]p[OK]e[OK]r[OK]_[OK]c[OK]a[OK]p[OK]i[OK]t[OK]a[OK]'[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]<[OK] [OK]u[OK]m[OK]b[OK]r[OK]a[OK]l[OK]e[OK]s[OK][[OK]'[OK]c[OK]a[OK]m[OK]a[OK]s[OK]_[OK]p[OK]e[OK]r[OK]_[OK]c[OK]a[OK]p[OK]i[OK]t[OK]a[OK]_[OK]p[OK]e[OK]r[OK]c[OK]e[OK]n[OK]t[OK]i[OK]l[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]1[OK] [OK]i[OK]f[OK] [OK]s[OK]u[OK]m[OK]([OK]c[OK]o[OK]n[OK]d[OK]i[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK]_[OK]a[OK]l[OK]t[OK]o[OK]_[OK]r[OK]i[OK]e[OK]s[OK]g[OK]o[OK])[OK] [OK]>[OK]=[OK] [OK]2[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]0[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]c[OK]r[OK]e[OK]a[OK]r[OK]_[OK]r[OK]e[OK]s[OK]u[OK]m[OK]e[OK]n[OK]_[OK]e[OK]s[OK]t[OK]a[OK]d[OK]i[OK]s[OK]t[OK]i[OK]c[OK]o[OK]([OK]d[OK]f[OK],[OK] [OK]g[OK]r[OK]u[OK]p[OK]o[OK]_[OK]c[OK]o[OK]l[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]C[OK]r[OK]e[OK]a[OK] [OK]r[OK]e[OK]s[OK]u[OK]m[OK]e[OK]n[OK] [OK]e[OK]s[OK]t[OK]a[OK]d[OK]Ã[OK]­[OK]s[OK]t[OK]i[OK]c[OK]o[OK] [OK]a[OK]g[OK]r[OK]u[OK]p[OK]a[OK]d[OK]o[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]m[OK]e[OK]n[OK] [OK]=[OK] [OK]d[OK]f[OK].[OK]g[OK]r[OK]o[OK]u[OK]p[OK]b[OK]y[OK]([OK]g[OK]r[OK]u[OK]p[OK]o[OK]_[OK]c[OK]o[OK]l[OK])[OK].[OK]a[OK]g[OK]g[OK]([OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]n[OK]a[OK]c[OK]i[OK]m[OK]i[OK]e[OK]n[OK]t[OK]o[OK]s[OK]'[OK]:[OK] [OK]'[OK]s[OK]u[OK]m[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]d[OK]e[OK]f[OK]u[OK]n[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK]'[OK]:[OK] [OK]'[OK]s[OK]u[OK]m[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]a[OK]s[OK]a[OK]_[OK]m[OK]o[OK]r[OK]t[OK]a[OK]l[OK]i[OK]d[OK]a[OK]d[OK]_[OK]f[OK]e[OK]t[OK]a[OK]l[OK]'[OK]:[OK] [OK]'[OK]m[OK]e[OK]a[OK]n[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]p[OK]r[OK]e[OK]s[OK]i[OK]o[OK]n[OK]_[OK]o[OK]b[OK]s[OK]t[OK]e[OK]t[OK]r[OK]i[OK]c[OK]a[OK]'[OK]:[OK] [OK]'[OK]m[OK]e[OK]a[OK]n[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]n[OK]u[OK]m[OK]_[OK]i[OK]n[OK]s[OK]t[OK]i[OK]t[OK]u[OK]c[OK]i[OK]o[OK]n[OK]e[OK]s[OK]'[OK]:[OK] [OK]'[OK]s[OK]u[OK]m[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK])[OK].[OK]r[OK]o[OK]u[OK]n[OK]d[OK]([OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]r[OK]e[OK]s[OK]u[OK]m[OK]e[OK]n[OK][OK]
[OK]